#!/usr/bin/bash

# report failed cron jobs
# use it like the follwoing cron:
# 00 03 * * * root rsnapshot daily || report rsnapshot

email=a.yousry@nileage.com
log=/var/log/

mail -s "$HOSTNAME backup failed" $email <<< "For more information check ${log}rsnapshot & ${log}dbbackup & ${log}cron"
